server:
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always

spring:
  application:
    name: home-guide-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local   # 激活 local 配置文件

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
